Repository hyochan/expo-iap, pull requests merged in 2025-08, with the labels that each got.

#134 fix: iOS hot reload issues with concurrent StoreKit operations
  .markdownlint.json
  CHANGELOG.md
  docs/docs/guides/ios-hot-reload-fix.md
  ios/ExpoIapModule.swift
  package.json
  src/useIap.ts
Labels: 📱 iOS, 🛠 bugfix

#160 feat: add unified purchaseToken support
  .vscode/launch.json
  android/src/main/java/expo/modules/iap/ExpoIapModule.kt
  docs/docs/api/types.md
  docs/docs/api/use-iap.md
  docs/docs/examples/basic-store.md
  docs/docs/examples/complete-impl.md
  docs/docs/examples/subscription-manager.md
  docs/docs/guides/getting-started.md
  example/__tests__/validate-receipt.test.tsx
  ios/ExpoIapModule.swift
  src/ExpoIap.types.ts
  src/index.ts
  src/types/ExpoIapAndroid.types.ts
  src/types/ExpoIapIos.types.ts
Labels: 🎯 feature

#162 fix: resolve type mismatches between iOS and Android
  CHANGELOG.md
  CLAUDE.md
  android/src/main/java/expo/modules/iap/ExpoIapModule.kt
  docs/blog/2025-07-23-v2-7-0-release.md
  docs/blog/2025-08-19-v2-8-1-release.md
  docs/docs/examples/basic-store.md
  docs/docs/examples/complete-impl.md
  docs/docs/examples/subscription-manager.md
  docs/docs/guides/faq.md
  docs/docs/guides/migration.md
  docs/docs/guides/purchases.md
  docs/docs/guides/troubleshooting.md
  docs/versioned_docs/version-2.6/examples/basic-store.md
  docs/versioned_docs/version-2.6/examples/complete-impl.md
  docs/versioned_docs/version-2.6/examples/subscription-manager.md
  docs/versioned_docs/version-2.6/guides/faq.md
  docs/versioned_docs/version-2.6/guides/purchases.md
  docs/versioned_docs/version-2.7/examples/basic-store.md
  docs/versioned_docs/version-2.7/examples/complete-impl.md
  docs/versioned_docs/version-2.7/examples/subscription-manager.md
  docs/versioned_docs/version-2.7/guides/faq.md
  docs/versioned_docs/version-2.7/guides/purchases.md
  example/__mocks__/expo-clipboard.ts
  example/__tests__/subscription-flow.test.tsx
  example/app/available-purchases.tsx
  example/app/purchase-flow.tsx
  example/app/subscription-flow.tsx
  example/bun.lock
  example/package.json
  ios/ExpoIapModule.swift
  src/ExpoIap.types.ts
  src/index.ts
  src/types/ExpoIapAndroid.types.ts
  src/types/ExpoIapIOS.types.ts
Labels: ፦ refactor, ❄️ types

#165 docs: add plugin in installation step
  docs/docs/installation.md
Labels: 📖 documentation

#178 refactor: modernize Android billing implementation
  android/src/main/java/expo/modules/iap/ExpoIapModule.kt
  android/src/main/java/expo/modules/iap/PlayUtils.kt
  android/src/main/java/expo/modules/iap/Types.kt
Labels: 🚽 migration

#180 Fix Android finishTransaction null error
  src/index.ts
Labels: 🛠 bugfix, 🤖 android
