Repository hyochan/expo-iap, pull requests merged in 2025-06, with the labels that each got.

#58 removed log "Applying expo-iap config plugin..."
  plugin/src/withIAP.ts
Labels: 🧹 chore

#60 [IOS] FIx IOS exceptions
  ios/ExpoIapModule.swift
Labels: 🍗 enhancement, 📱 iOS

#74 Removed dead links redirecting to managed vs bare documentation.
  iap.md
Labels: 📖 documentation

#75 Fix the broken documentation link in the documentation.
  iap.md
Labels: 📖 documentation, 🥢 typo

#78 docs: add setup guide
  README.md
  docs/SETUP_GUIDE.md
Labels: 📖 documentation

#79 refactor: centralize error codes in Types files
  android/src/main/java/expo/modules/iap/ExpoIapModule.kt
  android/src/main/java/expo/modules/iap/Types.kt
  ios/ExpoIapModule.swift
  ios/Types.swift
Labels: ፦ refactor
